configurations:
    - id: intellij_platform
      name: IntelliJ Platform
      description: Standard configurations for IntelliJ platform based projects with Java inspections
      qodanaYaml: intellij/qodana.yaml

    - id: ai_platform
      name: AI Platform
      description: Configurations for AI-platform based projects with JavaScript and AI inspections
      qodanaYaml: ai-products/qodana.yaml