# published to cloud, can be used in linters
# to cloud we publish effective configuration (merged with base)
configurations:
  - name: intellij-products
    directory: intellij-products
    base: base-config # inheritance inherits properties of qodana.yaml and includes the flexinspect inspections

  - name: ai-products
    directory: ai-products
    base: base-config # inheritance inherits properties of qodana.yaml and includes the flexinspect inspections

# not published to cloud, serve as base for public ones
internalConfigurations: # WIP name
  - name: base-config
    directory: global-base